/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package goHotel.view;

import javax.swing.ImageIcon;

/**
* AUTOR: GRUPO 3
 * PROYECTO
 * SEMANA 9
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/ImagenesProyecto/list.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        chmGestionReservas = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();
        chmGestionHoteles = new javax.swing.JCheckBoxMenuItem();
        chmGestionHabitaciones = new javax.swing.JCheckBoxMenuItem();
        chmTipoServicio = new javax.swing.JCheckBoxMenuItem();
        chmTipoHabitacion = new javax.swing.JCheckBoxMenuItem();
        chmGestionPaises = new javax.swing.JCheckBoxMenuItem();
        chmGestionPlanLealtad = new javax.swing.JCheckBoxMenuItem();
        chmGestionClientes = new javax.swing.JCheckBoxMenuItem();
        chmGestionEmpleados = new javax.swing.JCheckBoxMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu4 = new javax.swing.JMenu();
        chmSalir = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setIconImage(getIconImage());
        setIconImages(getIconImages());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesProyecto/MENUADOC.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setForeground(new java.awt.Color(0, 0, 0));
        jMenu1.setText("RESERVAS");

        chmGestionReservas.setBackground(new java.awt.Color(255, 255, 255));
        chmGestionReservas.setForeground(new java.awt.Color(0, 0, 0));
        chmGestionReservas.setSelected(true);
        chmGestionReservas.setText("Gestion Reservas");
        chmGestionReservas.setName("mnuGestionReservas"); // NOI18N
        chmGestionReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chmGestionReservasActionPerformed(evt);
            }
        });
        jMenu1.add(chmGestionReservas);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(255, 255, 255));
        jMenu2.setForeground(new java.awt.Color(0, 0, 0));
        jMenu2.setText("GESTION");

        chmGestionHoteles.setBackground(new java.awt.Color(255, 255, 255));
        chmGestionHoteles.setForeground(new java.awt.Color(0, 0, 0));
        chmGestionHoteles.setSelected(true);
        chmGestionHoteles.setText("Gestion de Hoteles");
        chmGestionHoteles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chmGestionHotelesActionPerformed(evt);
            }
        });
        jMenu2.add(chmGestionHoteles);

        chmGestionHabitaciones.setBackground(new java.awt.Color(255, 255, 255));
        chmGestionHabitaciones.setForeground(new java.awt.Color(0, 0, 0));
        chmGestionHabitaciones.setSelected(true);
        chmGestionHabitaciones.setText("Gestion de Habitaciones");
        jMenu2.add(chmGestionHabitaciones);

        chmTipoServicio.setBackground(new java.awt.Color(255, 255, 255));
        chmTipoServicio.setForeground(new java.awt.Color(0, 0, 0));
        chmTipoServicio.setSelected(true);
        chmTipoServicio.setText("Tipo de Servicio");
        jMenu2.add(chmTipoServicio);

        chmTipoHabitacion.setBackground(new java.awt.Color(255, 255, 255));
        chmTipoHabitacion.setForeground(new java.awt.Color(0, 0, 0));
        chmTipoHabitacion.setSelected(true);
        chmTipoHabitacion.setText("Tipos de Habitacion");
        jMenu2.add(chmTipoHabitacion);

        chmGestionPaises.setSelected(true);
        chmGestionPaises.setText("Gestión de Países");
        chmGestionPaises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chmGestionPaisesActionPerformed(evt);
            }
        });
        jMenu2.add(chmGestionPaises);

        chmGestionPlanLealtad.setBackground(new java.awt.Color(255, 255, 255));
        chmGestionPlanLealtad.setForeground(new java.awt.Color(0, 0, 0));
        chmGestionPlanLealtad.setSelected(true);
        chmGestionPlanLealtad.setText("Gestion de Planes de Lealtad");
        jMenu2.add(chmGestionPlanLealtad);

        chmGestionClientes.setBackground(new java.awt.Color(255, 255, 255));
        chmGestionClientes.setForeground(new java.awt.Color(0, 0, 0));
        chmGestionClientes.setSelected(true);
        chmGestionClientes.setText("Gestion de Clientes");
        jMenu2.add(chmGestionClientes);

        chmGestionEmpleados.setBackground(new java.awt.Color(255, 255, 255));
        chmGestionEmpleados.setForeground(new java.awt.Color(0, 0, 0));
        chmGestionEmpleados.setSelected(true);
        chmGestionEmpleados.setText("Gestion de Empleados");
        jMenu2.add(chmGestionEmpleados);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("LIMPIEZA");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Reporte de Ocupación");
        jMenu3.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("SALIR");

        chmSalir.setSelected(true);
        chmSalir.setText("Salir");
        chmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chmSalirActionPerformed(evt);
            }
        });
        jMenu4.add(chmSalir);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chmGestionReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chmGestionReservasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chmGestionReservasActionPerformed

    private void chmGestionHotelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chmGestionHotelesActionPerformed
       GestionHoteles gh = new GestionHoteles();
       gh.setVisible(true);
       gh.setLocationRelativeTo(null);
    }//GEN-LAST:event_chmGestionHotelesActionPerformed

    private void chmGestionPaisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chmGestionPaisesActionPerformed
       GestionPaises p = new GestionPaises();
       p.setVisible(true);
       p.setLocationRelativeTo(null);
    }//GEN-LAST:event_chmGestionPaisesActionPerformed

    private void chmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chmSalirActionPerformed
       System.exit(0);  
    }//GEN-LAST:event_chmSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem chmGestionClientes;
    private javax.swing.JCheckBoxMenuItem chmGestionEmpleados;
    private javax.swing.JCheckBoxMenuItem chmGestionHabitaciones;
    private javax.swing.JCheckBoxMenuItem chmGestionHoteles;
    private javax.swing.JCheckBoxMenuItem chmGestionPaises;
    private javax.swing.JCheckBoxMenuItem chmGestionPlanLealtad;
    private javax.swing.JCheckBoxMenuItem chmGestionReservas;
    private javax.swing.JCheckBoxMenuItem chmSalir;
    private javax.swing.JCheckBoxMenuItem chmTipoHabitacion;
    private javax.swing.JCheckBoxMenuItem chmTipoServicio;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
