/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package goHotel.view;

import goHotel.controller.LoginController;
import goHotel.controller.ServicioController;
import goHotel.model.ConsultasServicio;
import goHotel.model.Servicio;
import javax.swing.ImageIcon;
import javax.swing.JTextField;

/**
* AUTOR: GRUPO 3
 * PROYECTO
 * SEMANA 9
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
 
     */
    public Menu(String correo, String tipo) 
    {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/ImagenesProyecto/list.png")).getImage());
        String[] infoUsuario = LoginController.getUserInfo(correo, tipo);
        if (tipo.equalsIgnoreCase("Cliente")) 
        {
            mnuMantenimientos.setVisible(false);
            mnuLimpieza.setVisible(false);
        }
        jlCorreo.setText(infoUsuario[0]);
        jlTipo.setText(infoUsuario[1]);
        
     
        if (tipo.equalsIgnoreCase("Empleado")) 
        {
        String rol = infoUsuario[1].replace("Rol:", "").trim();
        switch (rol) 
        {
        case "Admin":
          mnuReservas.setVisible(true);
          mnuMantenimientos.setVisible(true);  
          mnuLimpieza.setVisible(true);
          break;

        case "Recepcion":
          mnuMantenimientos.setVisible(false);  
          mnuLimpieza.setVisible(false);
          break;
            
        case "Limpieza":
          mnuMantenimientos.setVisible(false);
          mnuReservas.setVisible(false);
          break;
        default:
            
            break;
    }
        }
    }
    
    public Menu() {
        // Llama al principal con valores por defecto
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/ImagenesProyecto/list.png")).getImage());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlCorreo = new javax.swing.JLabel();
        jlTipo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuReservas = new javax.swing.JMenu();
        chmGestionReservas = new javax.swing.JCheckBoxMenuItem();
        mnuMantenimientos = new javax.swing.JMenu();
        chmGestionHoteles = new javax.swing.JCheckBoxMenuItem();
        chmGestionHabitaciones = new javax.swing.JCheckBoxMenuItem();
        chmTipoServicio = new javax.swing.JCheckBoxMenuItem();
        chmTipoHabitacion = new javax.swing.JCheckBoxMenuItem();
        chmGestionPaises = new javax.swing.JCheckBoxMenuItem();
        chmGestionPlanLealtad = new javax.swing.JCheckBoxMenuItem();
        chmGestionClientes = new javax.swing.JCheckBoxMenuItem();
        chmGestionEmpleados = new javax.swing.JCheckBoxMenuItem();
        mnuLimpieza = new javax.swing.JMenu();
        chmReporteOcupacion = new javax.swing.JCheckBoxMenuItem();
        mnuSalir = new javax.swing.JMenu();
        chmSalir = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setIconImage(getIconImage());
        setIconImages(getIconImages());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlCorreo.setText("NombreUsuario");
        getContentPane().add(jlCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 180, 30));

        jlTipo.setText("RolAcceso");
        getContentPane().add(jlTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 160, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesProyecto/MenuFinal.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 580));

        mnuReservas.setText("RESERVAS");

        chmGestionReservas.setSelected(true);
        chmGestionReservas.setText("Gestion Reservas");
        chmGestionReservas.setName("mnuGestionReservas"); // NOI18N
        chmGestionReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chmGestionReservasActionPerformed(evt);
            }
        });
        mnuReservas.add(chmGestionReservas);

        jMenuBar1.add(mnuReservas);

        mnuMantenimientos.setText("MANTENIMIENTOS");

        chmGestionHoteles.setSelected(true);
        chmGestionHoteles.setText("Gestion Hoteles");
        chmGestionHoteles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chmGestionHotelesActionPerformed(evt);
            }
        });
        mnuMantenimientos.add(chmGestionHoteles);

        chmGestionHabitaciones.setSelected(true);
        chmGestionHabitaciones.setText("Gestion Habitaciones");
        chmGestionHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chmGestionHabitacionesActionPerformed(evt);
            }
        });
        mnuMantenimientos.add(chmGestionHabitaciones);

        chmTipoServicio.setSelected(true);
        chmTipoServicio.setText("Gestión Tipo Servicio");
        chmTipoServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chmTipoServicioActionPerformed(evt);
            }
        });
        mnuMantenimientos.add(chmTipoServicio);

        chmTipoHabitacion.setSelected(true);
        chmTipoHabitacion.setText("Gestión Tipos Habitación");
        chmTipoHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chmTipoHabitacionActionPerformed(evt);
            }
        });
        mnuMantenimientos.add(chmTipoHabitacion);

        chmGestionPaises.setSelected(true);
        chmGestionPaises.setText("Gestión Países");
        chmGestionPaises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chmGestionPaisesActionPerformed(evt);
            }
        });
        mnuMantenimientos.add(chmGestionPaises);

        chmGestionPlanLealtad.setSelected(true);
        chmGestionPlanLealtad.setText("Gestion Planes de Lealtad");
        mnuMantenimientos.add(chmGestionPlanLealtad);

        chmGestionClientes.setSelected(true);
        chmGestionClientes.setText("Gestion Clientes");
        mnuMantenimientos.add(chmGestionClientes);

        chmGestionEmpleados.setSelected(true);
        chmGestionEmpleados.setText("Gestion Empleados");
        mnuMantenimientos.add(chmGestionEmpleados);

        jMenuBar1.add(mnuMantenimientos);

        mnuLimpieza.setText("LIMPIEZA");

        chmReporteOcupacion.setSelected(true);
        chmReporteOcupacion.setText("Reporte de Ocupación");
        mnuLimpieza.add(chmReporteOcupacion);

        jMenuBar1.add(mnuLimpieza);

        mnuSalir.setText("SALIR");

        chmSalir.setSelected(true);
        chmSalir.setText("Salir");
        chmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chmSalirActionPerformed(evt);
            }
        });
        mnuSalir.add(chmSalir);

        jMenuBar1.add(mnuSalir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chmGestionReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chmGestionReservasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chmGestionReservasActionPerformed

    private void chmGestionHotelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chmGestionHotelesActionPerformed
       GestionHoteles gh = new GestionHoteles();
       gh.setVisible(true);
       gh.setLocationRelativeTo(null);
    }//GEN-LAST:event_chmGestionHotelesActionPerformed

    private void chmGestionPaisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chmGestionPaisesActionPerformed
       GestionPaises p = new GestionPaises();
       p.setVisible(true);
       p.setLocationRelativeTo(null);
    }//GEN-LAST:event_chmGestionPaisesActionPerformed

    private void chmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chmSalirActionPerformed
       System.exit(0);  
    }//GEN-LAST:event_chmSalirActionPerformed

    private void chmTipoHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chmTipoHabitacionActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_chmTipoHabitacionActionPerformed

    private void chmGestionHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chmGestionHabitacionesActionPerformed
        GestionHabitacion gha = new GestionHabitacion();
        gha.setVisible(true);
        gha.setLocationRelativeTo(null);
    }//GEN-LAST:event_chmGestionHabitacionesActionPerformed

    private void chmTipoServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chmTipoServicioActionPerformed
        Servicio m = new Servicio();
        ConsultasServicio q = new ConsultasServicio();
        GestionServicio v = new GestionServicio();
        new ServicioController(m, q, v);
        v.setLocationRelativeTo(null);
        v.setVisible(true);
    }//GEN-LAST:event_chmTipoServicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem chmGestionClientes;
    private javax.swing.JCheckBoxMenuItem chmGestionEmpleados;
    private javax.swing.JCheckBoxMenuItem chmGestionHabitaciones;
    private javax.swing.JCheckBoxMenuItem chmGestionHoteles;
    private javax.swing.JCheckBoxMenuItem chmGestionPaises;
    private javax.swing.JCheckBoxMenuItem chmGestionPlanLealtad;
    private javax.swing.JCheckBoxMenuItem chmGestionReservas;
    private javax.swing.JCheckBoxMenuItem chmReporteOcupacion;
    private javax.swing.JCheckBoxMenuItem chmSalir;
    private javax.swing.JCheckBoxMenuItem chmTipoHabitacion;
    private javax.swing.JCheckBoxMenuItem chmTipoServicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlCorreo;
    private javax.swing.JLabel jlTipo;
    private javax.swing.JMenu mnuLimpieza;
    private javax.swing.JMenu mnuMantenimientos;
    private javax.swing.JMenu mnuReservas;
    private javax.swing.JMenu mnuSalir;
    // End of variables declaration//GEN-END:variables
}
